[build]
base = "lambda-notes-vue/"
publish = "lambda-notes-vue/build/"
command = "yarn build"

# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true # Ensure that we always redirect